# Generated by Django 4.2.20 on 2025-11-14 18:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(blank=True, choices=[('w', 'White'), ('ba', 'Black or African American'), ('na', 'American Indian or Alaska Native'), ('as', 'Asian'), ('nhpi', 'Native Hawaiian or Pacific Islander'), ('hl', 'Hispanic or Latino/a'), ('me', 'Middle Eastern'), ('bm', 'Biracial or Multiracial'), ('o', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], db_index=True, max_length=25, null=True, verbose_name='Race or Ethnicity')),
                ('employment_status', models.CharField(blank=True, choices=[('efw', 'Employed for wages'), ('selfemployed', 'Self-employed'), ('student', 'Student'), ('homemaker', 'Homemaker'), ('oowlfw', 'Out of work and looking for work'), ('oownclfw', 'Out of work but not currently looking for work'), ('military', 'Military'), ('retired', 'Retired'), ('utw', 'Unable to work'), ('prefer-not-to-say', 'Prefer not to say')], db_index=True, max_length=20, null=True, verbose_name='Employment Status')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid zipcode', regex='^(\\d{5}([\\-]\\d{4})?)$')], verbose_name='Zip Code')),
                ('enrolled_in_school', models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Are you currently enrolled in school?')),
                ('enrolled_in_school_type', models.CharField(blank=True, choices=[('hs', 'High School'), ('two-year', '2-year/technical college'), ('four-year', '4-year college or university'), ('grad', 'Graduate School'), ('ne', 'Not Enrolled'), ('instructor', 'Instructor'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Type of Current School Enrollment')),
                ('local_community_living', models.CharField(blank=True, choices=[('ls', 'A large city'), ('su', 'A suburb near a large city'), ('sct', 'A small city or town'), ('ra', 'A rural area'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Thinking about your local community, which of the following best describes the place you live now?')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
