# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[(b'w', b'White'), (b'hl', b'Hispanic or Latino'), (b'ba', b'Black or African American'), (b'na', b'Native American or American Indian'), (b'api', b'Asian / Pacific Islander'), (b'other', b'Other')], db_index=True, max_length=6, null=True, verbose_name=b'Ethnicity'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='favorite_movie',
            field=models.CharField(max_length=100, verbose_name=b'Fav Flick'),
        ),
    ]
