# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-29 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0003_extrainfo_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='zip',
            field=models.CharField(blank=True, help_text=b'Zipcode', max_length=10, null=True),
        ),
    ]
