# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 21:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0004_extrainfo_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid zipcode', regex=b'^\\d{5}(?:[-\\s]\\d{4})?$')], verbose_name=b'Zip Code'),
        ),
    ]
