# Generated by Django 3.2.10 on 2022-02-01 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0007_auto_20190626_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('efw', 'Employed for wages'), ('selfemployed', 'Self-employed'), ('student', 'Student'), ('homemaker', 'Homemaker'), ('oowlfw', 'Out of work and looking for work'), ('oownclfw', 'Out of work but not currently looking for work'), ('military', 'Military'), ('retired', 'Retired'), ('utw', 'Unable to work'), ('other', 'Other')], db_index=True, max_length=20, null=True, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('w', 'White'), ('hl', 'Hispanic or Latino'), ('ba', 'Black or African American'), ('na', 'Native American or American Indian'), ('api', 'Asian / Pacific Islander'), ('other', 'Other')], db_index=True, max_length=6, null=True, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid zipcode', regex='^(\\d{5}([\\-]\\d{4})?)$')], verbose_name='Zip Code'),
        ),
    ]
