# Generated by Django 3.2.13 on 2022-08-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0008_auto_20220201_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='enrolled_in_school',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Are you currently enrolled in school?'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='enrolled_in_school_type',
            field=models.CharField(blank=True, choices=[('hs', 'High School or GED'), ('two-year', '2-year degree'), ('four-year', '4-year degree'), ('grad', 'Graduate School'), ('o', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Enrolled in school type'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='local_community_living',
            field=models.CharField(blank=True, choices=[('ls', 'A large city'), ('su', 'A suburb near a large city'), ('ra', 'A rural area'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Local Community Living'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('w', 'White'), ('hl', 'Hispanic or Latino/a'), ('ba', 'Black or African American'), ('na', 'American Indian or Alaska Native'), ('as', 'Asian'), ('nhpi', 'Native Hawaiian or Pacific Islander'), ('me', 'Middle Eastern'), ('bm', 'Biracial or Multiracial'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], db_index=True, max_length=25, null=True, verbose_name='Ethnicity'),
        ),
    ]
