# Generated by Django 3.2.13 on 2022-08-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0009_auto_20220808_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='enrolled_in_school_type',
            field=models.CharField(blank=True, choices=[('hs', 'High School or GED'), ('two-year', '2-year/technical college'), ('four-year', '4-year college or university'), ('grad', 'Graduate School'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Enrolled in school type'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='local_community_living',
            field=models.CharField(blank=True, choices=[('ls', 'A large city'), ('su', 'A suburb near a large city'), ('sct', 'A small city or town'), ('ra', 'A rural area'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Local Community Living'),
        ),
    ]
