# Generated by Django 3.2.13 on 2022-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0010_auto_20220812_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('efw', 'Employed for wages'), ('selfemployed', 'Self-employed'), ('student', 'Student'), ('homemaker', 'Homemaker'), ('oowlfw', 'Out of work and looking for work'), ('oownclfw', 'Out of work but not currently looking for work'), ('military', 'Military'), ('retired', 'Retired'), ('utw', 'Unable to work'), ('prefer-not-to-say', 'Prefer not to say')], db_index=True, max_length=20, null=True, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='enrolled_in_school_type',
            field=models.CharField(blank=True, choices=[('hs', 'High School'), ('two-year', '2-year/technical college'), ('four-year', '4-year college or university'), ('grad', 'Graduate School'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='In which type of school are you enrolled?'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('w', 'White'), ('ba', 'Black or African American'), ('na', 'American Indian or Alaska Native'), ('as', 'Asian'), ('nhpi', 'Native Hawaiian or Pacific Islander'), ('hl', 'Hispanic or Latino/a'), ('me', 'Middle Eastern'), ('bm', 'Biracial or Multiracial'), ('prefer-not-to-say', 'Prefer not to say')], db_index=True, max_length=25, null=True, verbose_name='How do you identify based on race and ethnicity?'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='local_community_living',
            field=models.CharField(blank=True, choices=[('ls', 'A large city'), ('su', 'A suburb near a large city'), ('sct', 'A small city or town'), ('ra', 'A rural area'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Thinking about your local community, which of the following best describes the place you live now?'),
        ),
    ]
