# Generated by Django 3.2.13 on 2022-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0011_auto_20220812_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrainfo',
            name='ethnicity_free_input',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Please specify your ethnicity'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='gender_free_input',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Please specify your Gender'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='enrolled_in_school_type',
            field=models.CharField(blank=True, choices=[('hs', 'High School'), ('two-year', '2-year/technical college'), ('four-year', '4-year college or university'), ('grad', 'Graduate School'), ('o', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], default=('prefer-not-to-say', 'Prefer not to say'), max_length=25, null=True, verbose_name='In which type of school are you enrolled?'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('w', 'White'), ('ba', 'Black or African American'), ('na', 'American Indian or Alaska Native'), ('as', 'Asian'), ('nhpi', 'Native Hawaiian or Pacific Islander'), ('hl', 'Hispanic or Latino/a'), ('me', 'Middle Eastern'), ('bm', 'Biracial or Multiracial'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], db_index=True, max_length=25, null=True, verbose_name='How do you identify based on race and ethnicity?'),
        ),
    ]
