# Generated by Django 4.2.19 on 2025-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_reg_form', '0013_alter_extrainfo_enrolled_in_school_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='enrolled_in_school_type',
            field=models.CharField(blank=True, choices=[('hs', 'High School'), ('two-year', '2-year/technical college'), ('four-year', '4-year college or university'), ('grad', 'Graduate School'), ('ne', 'Not Enrolled'), ('instructor', 'Instructor'), ('prefer-not-to-say', 'Prefer not to say')], max_length=25, null=True, verbose_name='Type of Current School Enrollment'),
        ),
    ]
